title: "Ron Payne Jr"
tagline: "Retro Ron â€” your friendly neighborhood I.T. guy"
description: "Retro games, retro tech, and IT/Desktop Support notes by Ron Payne Jr (Retro Ron)."
author: ""

theme: minima
show_excerpts: true

permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/ArcadeRonin" }

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
